### ISSUE TITLE
parse error by constraints with check

### ISSUE THREAD

**Issue by panwlodek** [qweeze/pg_diagram#11]
/home/wlodek/.local/bin/pg_diagram --format svg -o lolo.svg lolo.sql

Could not parse statement:
CREATE TABLE public."tp_timeentry" (
    id integer NOT NULL,
    line_no integer,
    date date NOT NULL,
    worked double precision NOT NULL,
    billable double precision NOT NULL,
    comment text NOT NULL,
    sub_account_id integer NOT NULL,
    time_file_id integer NOT NULL,
    CONSTRAINT "tp_timeentry_line_no_check" CHECK ((line_no >= 0))
);

I opened already following issue by sqlparse (s.: https://github.com/andialbrecht/sqlparse/issues/729 ) but the author proved, that it is not an error in psqlparse.

By the way: thanks for pg_diagram!!!!

**Comment by 1AB9502** [comment]
ran into this as well, I wonder if there is a workaround

**Comment by michaelb87** [comment]
Same problem. Python 3.11

**Comment by IuriKintschev** [comment]
Same problem

**Comment by qweeze** [comment]
Oh sorry, I wasn't following this project. It's probably too late but I fixed the bug with parsing
